#!/usr/bin/python
import sys
sys.path.append("/home/")
#sys.path.append("/home/llhuii/openstack")

from hyperservice import server

if __name__ == "__main__":
    sys.exit(server.main('hyperservice'))
